# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-19 21:15
from __future__ import unicode_literals

import app_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorcomments',
            old_name='reply_id',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='floorcomments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bar_id',
            new_name='bar',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='writer_id',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='postfloor',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postfloor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postphotos',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='userdetailmsg',
            name='background_pic',
            field=models.ImageField(blank=True, upload_to=app_api.models.photo_path, verbose_name='个人中心背景'),
        ),
    ]
