# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_auto_20190419_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorcomments',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_comment', to='app_api.PostFloor', verbose_name='回复的楼'),
        ),
        migrations.AlterField(
            model_name='floorcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='app_api.UserAll', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bar', to='app_api.PostBars', verbose_name='所属吧'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_writer', to='app_api.UserAll', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='postbars',
            name='feature',
            field=models.ManyToManyField(to='app_api.Tags', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='postbars',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_owner', to='app_api.UserAll', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='postfloor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_floor', to='app_api.Post', verbose_name='所属吧'),
        ),
        migrations.AlterField(
            model_name='postfloor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_writer', to='app_api.UserAll', verbose_name='作者'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('create_time', 'title')]),
        ),
    ]
