# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_auto_20190421_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorcomments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='显示状态'),
        ),
    ]
