# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_floorcomments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorcomments',
            name='replied_comment',
            field=models.IntegerField(default=0, verbose_name='回复评论'),
        ),
    ]
