# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_floorcomments_replied_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('read_status', models.BooleanField(default=False, verbose_name='消息已读状态')),
                ('display_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.Post')),
            ],
        ),
        migrations.RenameField(
            model_name='userdetailmsg',
            old_name='user_msg',
            new_name='user',
        ),
        migrations.AddField(
            model_name='postfloor',
            name='read_status',
            field=models.BooleanField(default=False, verbose_name='楼主已读状态'),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='display_status',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='userwatching',
            name='display_status',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='userwatching',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='postbars',
            name='name',
            field=models.CharField(max_length=30, verbose_name='吧名'),
        ),
        migrations.AlterField(
            model_name='postfloor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_floor', to='app_api.Post', verbose_name='帖子'),
        ),
        migrations.AlterField(
            model_name='userdetailmsg',
            name='collections',
            field=models.ManyToManyField(related_name='user_collection', to='app_api.Post', verbose_name='收藏的帖子'),
        ),
        migrations.AddField(
            model_name='userpraise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.UserDetailMsg'),
        ),
        migrations.AddField(
            model_name='userdetailmsg',
            name='praise',
            field=models.ManyToManyField(blank=True, related_name='user_praise', through='app_api.UserPraise', to='app_api.Post', verbose_name='点赞的帖子'),
        ),
    ]
