# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_auto_20190424_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmsg',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别'),
        ),
    ]
