# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-01 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_auto_20190501_1256'),
        ('app_api', '0006_auto_20190424_1431'),
    ]

    operations = [
    ]
