# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_merge_20190501_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorcomments',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息状态'),
        ),
        migrations.AddField(
            model_name='postfloor',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息状态'),
        ),
        migrations.AlterField(
            model_name='floorcomments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='评论显示状态'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='展示状态'),
        ),
        migrations.AlterField(
            model_name='userpraise',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='展示状态'),
        ),
        migrations.AlterField(
            model_name='userwatching',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='删除状态'),
        ),
        migrations.AlterIndexTogether(
            name='userall',
            index_together=set([('username', 'email')]),
        ),
    ]
