# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_auto_20190502_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbars',
            name='short_description',
            field=models.TextField(default='无', verbose_name='吧的简介'),
        ),
        migrations.AlterField(
            model_name='floorcomments',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息展示状态'),
        ),
        migrations.AlterField(
            model_name='postfloor',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息展示状态'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息展示状态'),
        ),
        migrations.AlterField(
            model_name='userpraise',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息展示状态'),
        ),
        migrations.AlterField(
            model_name='userwatching',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='消息展示状态'),
        ),
    ]
