# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_auto_20190503_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, verbose_name='u敏感词')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userpraise',
            options={'verbose_name': '点赞', 'verbose_name_plural': '点赞'},
        ),
    ]
