# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0012_auto_20190512_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitiveword',
            options={'verbose_name': '敏感词', 'verbose_name_plural': '敏感词'},
        ),
        migrations.AlterField(
            model_name='sensitiveword',
            name='word',
            field=models.CharField(max_length=40, verbose_name='敏感词'),
        ),
    ]
