# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0013_auto_20190512_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={'verbose_name': '用户关注的人', 'verbose_name_plural': '用户关注的人'},
        ),
        migrations.AlterModelOptions(
            name='userwatching',
            options={'verbose_name': '用户关注的吧', 'verbose_name_plural': '用户关注的吧'},
        ),
        migrations.AddField(
            model_name='userfollow',
            name='info_status',
            field=models.BooleanField(default=False, verbose_name='消息是否被删除'),
        ),
        migrations.AddField(
            model_name='userpraise',
            name='info_status',
            field=models.BooleanField(default=False, verbose_name='消息是否被删除'),
        ),
        migrations.AddField(
            model_name='userwatching',
            name='info_status',
            field=models.BooleanField(default=False, verbose_name='消息是否被删除'),
        ),
        migrations.AlterField(
            model_name='userpraise',
            name='display_status',
            field=models.BooleanField(default=True, verbose_name='信息展示状态'),
        ),
    ]
